### ISSUE TITLE
1.4.4b not loading modloader

### ISSUE THREAD

**Issue by OvOPlant** [drakeerv/OvO#1]
i tried all the links i could and it's not working in version 1.4.4b:
[ovo-alpha.vercel.app](https://ovo-alpha.vercel.app/)
[ovo-drakeerv.vercel.app](https://ovo-drakeerv.vercel.app/)
[ovo-git-main-drakeerv.vercel.app](https://ovo-git-main-drakeerv.vercel.app/)

and this link isnt updated at all:
[ovo.drakefletcher2.repl.co/](https://ovo.drakefletcher2.repl.co/)

**Comment by drakeerv** [comment]
Fixed
